name: cellpy_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9
  - pip
  - numpy
  - openpyxl
  - xlrd
  - matplotlib
  - cryptography
  - click
  - scipy
  - pandas >=1.4.0
  - pytables >=3.5.1
  - setuptools
  - ruamel.yaml
  - pyodbc
  - coverage
  - wheel
  - flake8
  - Sphinx
  - PyGithub
  - watchdog
  - pytest
  - black
  - twine
  - invoke
  - conda-build
  - ripgrep
  - conda-verify
  - anaconda-client
  - lmfit
  - cookiecutter
  - tqdm
  - pandoc
  - ipykernel
  - ipywidgets
  - python-box
  - sqlalchemy >=2.0.0
  - pint >=0.20.1
  - seaborn
  - plotly
  - python-kaleido ==0.1.*
  - pip:
    - sqlalchemy-access
    - pytest-benchmark
    - pytest-timeout
    - requests
    - nbsphinx
    - sphinx-rtd-theme
    - build
    - python-dotenv
    - nox
