name: cellpy
channels:
    - conda-forge
    - pyviz
dependencies:
    - python >=3.9
    - pip
    - numpy
    - openpyxl
    - xlrd
    - matplotlib
    - cryptography
    - click
    - scipy
    - pandas >=1.5.0
    - setuptools
    - ruamel.yaml
    - pyodbc
    - PyGithub
    - cookiecutter
    - tqdm
    - ipython
    - ipywidgets
    - lmfit
    - ipykernel
    - holoviz
    - hdf5
    - pytables >=3.6.1
    - python-box
    - pytest
    - invoke
    - jupyter
    - jupyterlab
    - sqlalchemy >=2.0.0
    - pint
    - plotly
    - pip:
        - sqlalchemy-access
