name: cellpy
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - numpy
    - openpyxl
    - xlrd
    - cryptography
    - click
    - scipy
    - pandas
    - setuptools
    - ruamel.yaml
    - pyodbc
    - PyGithub
    - cookiecutter
    - tqdm
    - dateparser
    - hdf5
    - pytables
    - python-box
    - pint
    - sqlalchemy
    - python-dotenv
    - fabric
    - lmfit
    - matplotlib
    - plotly
    - ipython
    - ipywidgets
    - ipykernel
    - rich
    - pip:
        - sqlalchemy-access

