name: cellpy
channels:
    - conda-forge
dependencies:
    - click
    - cookiecutter
    - cryptography
    - dateparser
    - fabric
    - hdf5
    - ipykernel
    - ipython
    - ipywidgets
    - lmfit
    - matplotlib
    - numpy >= 2.0
    - openpyxl
    - pandas < 3
    - pint
    - pip
    - plotly
    - pygithub
    - pyodbc
    - pytables
    - python-box
    - python-dotenv
    - python >= 3.10
    - requests
    - rich
    - ruamel.yaml
    - scipy
    - setuptools
    - sqlalchemy
    - sqlalchemy-access
    - tqdm
    - xlrd
# This version of kaleido is not available for macOS M-chip:
    - kaleido==0.1.*
    - jinja2_time
    - charset-normalizer


