name: cellpy_dev
channels:
    - conda-forge
    - defaults
dependencies:
    - PyGithub
    - charset-normalizer
    - click
    - cookiecutter
    - coverage
    - cryptography
    - dateparser
    - fabric
    - hdf5
    - lmfit
    - matplotlib
    - nbmake
    - numpy>=2
    - openpyxl
    - pandas<3
    - pint
    - pip
    - plotly
    - pyodbc
    - pytables
    - pytest
    - pytest-benchmark
    - pytest-timeout
    - python
    - python-box
    - python-dotenv
    - requests
    - rich
    - ruamel.yaml
    - scipy
    - setuptools
    - sqlalchemy
    - sqlalchemy-access
    - tqdm
    - xlrd
    - pip:
        - jinja2_time



