name: cellpy_dev
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.9
    - pip
    - numpy
    - openpyxl
    - xlrd
    - matplotlib
    - cryptography
    - click
    - scipy
    - pandas
    - setuptools
    - ruamel.yaml
    - pyodbc
    - PyGithub
    - cookiecutter
    - tqdm
    - lmfit
    - hdf5
    - pytables
    - python-box
    - pint
    - sqlalchemy
    - python-dotenv
    - fabric
    - rich
    - dateparser
    - coverage
    - pytest
    - pytest-timeout
    - pytest-benchmark
    - jinja2_time
    - pip:
        - sqlalchemy-access


