name: cellpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9
  - pip
  - numpy
  - openpyxl
  - matplotlib
  - cryptography
  - click
  - scipy
  - pandas
  - pytables >=3.5.1
  - setuptools
  - ruamel.yaml
  - pyodbc
  - Sphinx
  - tqdm
  - python-box
  - pandoc
  - ipykernel
  - pint
  - pip:
    - nbsphinx
    - python-dotenv
    - fabric

